const exp = require('express');
const router = exp.Router();
const imgUpload = require('../../helpers/image-upload');
const adminController = require('../../controllers/admin');
const isAuth = require('../../middlewares/auth');
router.get("/create", isAuth, adminController.get_course_create);
router.post("/create", isAuth, imgUpload.single('img'), adminController.post_course_create);
router.get("/edit/:courseId", isAuth, adminController.get_course_edit);
router.post("/edit/:courseId", isAuth, imgUpload.single('img'), adminController.post_course_edit);
router.get("/delete/:courseId", isAuth, adminController.get_course_delete);
router.post("/delete/:courseId", isAuth, adminController.post_course_delete);
router.get("/", isAuth, adminController.get_course_list);
module.exports = router;
